version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - internal_net
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=random_hash_with_nice_something
  redis:
    image: redis:alpine
    networks:
      - internal_net
    ports:
      - 6379:6379
  app:
    image: kameike/simple_server:9923ea6559274962fcfdd361f7ec6cbdb456a8dd 
    ports:
      - 8080:3000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - appnet
      - internal_net
    volumes:
      - $PWD:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_USERNAME=user
networks:
  appnet:
  internal_net:
    internal: true
