version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - appnet
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
  redis:
    image: redis:alpine
    networks:
      - appnet
    ports:
      - 6379:6379
  app:
    build: .
    ports:
      - 8080:3000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - appnet
    volumes:
      - $PWD:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD=password
      - DB_NAME=database
      - DB_USERNAME=user
networks:
  appnet:
